apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc
spec:
  storageClassName: manual
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteOnce
  resources:
      requests:
        storage: 10Gi  
